spring.application.name=BE-U2-W1-L4
spring.datasource.url=jdbc:postgresql://localhost:5432/BE-U2-W1-L4
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true